# Generated by Django 3.2.9 on 2022-12-05 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FinishKingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
            ],
        ),
        migrations.CreateModel(
            name='FinishQueenGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionImageKing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='img/selection/king/%y/%mm/%dd')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionImageQueen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='img/selection/queen/%y/%mm/%dd')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionKing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('fblink', models.TextField(null=True)),
                ('iglink', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectionQueen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('fblink', models.TextField(null=True)),
                ('iglink', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotingM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_start', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=True)),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='OtherIncome',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='products',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='user',
        ),
        migrations.RemoveField(
            model_name='soldproduct',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='SoldProduct',
        ),
        migrations.AddField(
            model_name='votingm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selectionqueen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selectionqueen',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.votingm'),
        ),
        migrations.AddField(
            model_name='selectionking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selectionking',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.votingm'),
        ),
        migrations.AddField(
            model_name='selectionimagequeen',
            name='sk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.selectionqueen'),
        ),
        migrations.AddField(
            model_name='selectionimagequeen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selectionimageking',
            name='sk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.selectionking'),
        ),
        migrations.AddField(
            model_name='selectionimageking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finishqueengroup',
            name='selection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.selectionqueen'),
        ),
        migrations.AddField(
            model_name='finishkinggroup',
            name='selection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.selectionking'),
        ),
        migrations.AddField(
            model_name='device',
            name='votingm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='app.votingm'),
        ),
    ]
