# Generated by Django 3.2.9 on 2024-01-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_votingm_votingcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionking',
            name='address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='selectionking',
            name='age',
            field=models.TextField(default='18', null=True),
        ),
        migrations.AddField(
            model_name='selectionking',
            name='hobbies',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='selectionqueen',
            name='address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='selectionqueen',
            name='age',
            field=models.TextField(default='18', null=True),
        ),
        migrations.AddField(
            model_name='selectionqueen',
            name='hobbies',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='finishkinggroup',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_d', to='app.selectionking'),
        ),
        migrations.AlterField(
            model_name='finishqueengroup',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_d', to='app.selectionqueen'),
        ),
    ]
