# Generated by Django 3.2.9 on 2022-12-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionking',
            name='profileimage',
            field=models.ImageField(null=True, upload_to='img/selection/profile/%y/%mm/%dd'),
        ),
        migrations.AddField(
            model_name='selectionqueen',
            name='profileimage',
            field=models.ImageField(null=True, upload_to='img/selection/profile/%y/%mm/%dd'),
        ),
        migrations.AlterField(
            model_name='selectionking',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sel_king', to='app.votingm'),
        ),
        migrations.AlterField(
            model_name='selectionqueen',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sel_queen', to='app.votingm'),
        ),
    ]
