# Generated by Django 3.2.9 on 2022-12-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221208_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionking',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='selectionqueen',
            name='is_male',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='votingm',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
    ]
